version: '2.2'
volumes:
  jenkins-data:
services:
  jenkins:
    init: true
    build:
      context: .
      dockerfile: jenkins-bootstrap-shared/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - 'jenkins-data:/var/lib/jenkins'
